### ISSUE TITLE
"docker run..." command not working.

### ISSUE THREAD

**Issue by IfuChan** [sftekin/spatio-temporal-weather-forecasting#5]
Hi, the "docker build..." command ran smoothly and the Docker image was created however when I try to run "docker run -dit --name weather_model --gpus all --rm weather:v1 python run.py", in the terminal of VS Code, I get a large random letters as output in a single line then the process terminates. In the docker app, i can see the container being created then goes away instantly. Could you please help me out here.

**Comment by Neo-101** [comment]
@IfuChan @sftekin Hi guys, I have encountered the same problem, is there any solution?
